site_name: Drillbotics® Guidelines
site_description: Official, versioned Drillbotics competition rules and resources.
site_url: https://Open-Source-Drilling-Community.github.io/drillbotics-guidelines/
repo_url: https://github.com/Open-Source-Drilling-Community/drillbotics-guidelines 
repo_name: Drillbotics Guidelines
edit_uri: edit/master/docs/

# Copyright
copyright: Copyright &copy; 2015 - 2025 SPE Drillbotics


theme:
  name: material
  logo: _assets/images/logos/drillbotics-logo-bw.png
  favicon: _assets/images/logos/favicon-bw.svg
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    

  
  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle
  palette:
    - scheme: default
      primary: "#0d47a1"
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: "#90caf9"
      accent:  cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Open-Source-Drilling-Community/drillbotics-guidelines 
    - icon: fontawesome/solid/envelope
      link: mailto:competition@Drillbotics.com
  generator: false
  status:
    new: Recently added
    updated: Updated this release
    deprecated: Deprecated
  version:
    provider: mike

plugins:
  - search
  - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
      timezone: America/Chicago
      type: date
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - redirects
  - htmlproofer:
      raise_error: true
      validate_external_urls: false
      ignore_urls:
        - 'mailto:'
        - 'https://github.com/Open-Source-Drilling-Community/*'
        - 'https://d-wis.org/*'
        - 'https://www.osha.gov/*'
        - 'https://webevents.spe.org/*'
        - 'https://www.mathworks.com/*'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - _assets/scripts/announcement.js
  - _assets/scripts/sponsors-ribbon.js
  - _assets/scripts/copy-markdown.js
  - _assets/scripts/mermaid-theme.js
  - _assets/scripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - _assets/scripts/abbr-tooltips.js

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - def_list
  - md_in_html
  - tables
  - pymdownx.highlight
  - toc:
      permalink: true
  # Ensure snippet includes like `--8<-- "_includes/file.md"` work
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs
        - .
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes

strict: true

exclude_docs: |
  _includes/**

nav:
  - Home: index.md
  - Competition:
      - Overview: competition/index.md
      - About: competition/overview.md
      - Timeline & Milestones: competition/timeline.md
      - Upcoming Dates: competition/upcoming.md
      - Rules & Scoring: competition/rules-scoring.md
      - Safety: competition/safety.md
  - Tracks:
      - Overview: tracks/index.md
      - Deliverables (V vs P): tracks/deliverables.md
      - Mode Virtual (V):
          - Overview: tracks/group-a/overview.md
          - Technical Specs: tracks/group-a/technical-specs.md
          - Deliverables: tracks/group-a/deliverables.md
          - Judging: tracks/group-a/judging.md
      - Mode Physical (P):
          - Overview: tracks/group-b/overview.md
          - Safety & Risk: tracks/group-b/safety.md
          - Hardware: tracks/group-b/hardware.md
          - Autonomy & Control: tracks/group-b/autonomy.md
          - Deliverables & Testing: tracks/group-b/deliverables.md
          - Judging: tracks/group-b/judging.md
  - Resources:
      - FAQ: faq.md
      - Downloads: resources/downloads.md
      - Tags: tags.md
      - Official Site (drillbotics.com): https://drillbotics.com/
      - Archives (Previous Reports): https://drillbotics.com/archives/
  - Archive:
      - 2024:
          - Group A (Virtual): 2024/group-a.md
          - Group B (Physical): 2024/group-b.md
          - FAQ: 2024/faq.md
  - Changelog: changelog.md
  - Contributor Guide: contributor-guide.md
